#!/bin/bash
# Download country CIDR blocks from ipdeny.com and generate Apache blocking rules.
# Runs at container startup and weekly via update_geoip.sh (cron).
# Cache files are reused when fresh (< MAX_AGE_DAYS) to avoid redundant downloads.
#
# Env var:
#   BLOCKED_COUNTRIES  comma-separated ISO 3166-1 alpha-2 codes (e.g. CN,RU,KP)
#                      empty = geo-blocking disabled

GEOIP_BLOCK_CONF=/etc/apache2/conf-enabled/geoip-block.conf
CACHE_DIR=/var/cache/geoip-block
IPDENY_URL="https://www.ipdeny.com/ipblocks/data/aggregated"
MAX_AGE_DAYS=7

# Read BLOCKED_COUNTRIES from state file if not set in environment (cron context)
if [ -z "$BLOCKED_COUNTRIES" ] && [ -f "$CACHE_DIR/.countries" ]; then
    BLOCKED_COUNTRIES=$(cat "$CACHE_DIR/.countries")
fi

if [ -z "$BLOCKED_COUNTRIES" ]; then
    echo "GeoIP: BLOCKED_COUNTRIES not set — geo-blocking disabled"
    rm -f "$GEOIP_BLOCK_CONF"
    exit 0
fi

# Validate format: comma-separated ISO 3166-1 alpha-2 uppercase codes
if ! echo "$BLOCKED_COUNTRIES" | grep -qE '^[A-Z]{2}(,[A-Z]{2})*$'; then
    echo "ERROR: BLOCKED_COUNTRIES must be comma-separated ISO 3166-1 alpha-2 codes (e.g. CN,RU,KP)" >&2
    exit 1
fi

mkdir -p "$CACHE_DIR"

# Detect if the country list has changed since last run
COUNTRIES_CHANGED=false
if [ -f "$CACHE_DIR/.countries" ]; then
    saved=$(cat "$CACHE_DIR/.countries")
    [ "$saved" != "$BLOCKED_COUNTRIES" ] && COUNTRIES_CHANGED=true
fi

# Returns 0 (true) if the cache file is missing or older than MAX_AGE_DAYS
is_stale() {
    local file="$1"
    [ ! -f "$file" ] || [ -n "$(find "$file" -mtime "+${MAX_AGE_DAYS}" 2>/dev/null)" ]
}

# Check if all cache files are fresh and the conf already exists
if [ -f "$GEOIP_BLOCK_CONF" ] && ! $COUNTRIES_CHANGED; then
    ALL_FRESH=true
    for code in $(echo "$BLOCKED_COUNTRIES" | tr ',' '\n'); do
        lower=$(echo "$code" | tr '[:upper:]' '[:lower:]')
        if is_stale "$CACHE_DIR/${lower}.zone"; then
            ALL_FRESH=false
            break
        fi
    done
    if $ALL_FRESH; then
        echo "GeoIP: cache is fresh (< ${MAX_AGE_DAYS} days) and conf exists — skipping update"
        exit 0
    fi
fi

# Persist the country list for cron-based updates (cron does not inherit Docker env vars)
echo "$BLOCKED_COUNTRIES" > "$CACHE_DIR/.countries"

RULES_FILE=$(mktemp)
TOTAL_BLOCKS=0
FAILED=""

for code in $(echo "$BLOCKED_COUNTRIES" | tr ',' '\n'); do
    lower=$(echo "$code" | tr '[:upper:]' '[:lower:]')
    cache_file="$CACHE_DIR/${lower}.zone"
    url="${IPDENY_URL}/${lower}-aggregated.zone"

    if is_stale "$cache_file" || $COUNTRIES_CHANGED; then
        echo "GeoIP: downloading CIDR list for ${code}..."
        if curl -sf --max-time 30 -o "${cache_file}.tmp" "$url" && [ -s "${cache_file}.tmp" ]; then
            mv "${cache_file}.tmp" "$cache_file"
            count=$(wc -l < "$cache_file")
            echo "GeoIP: ${code} — ${count} CIDR blocks (updated)"
            TOTAL_BLOCKS=$((TOTAL_BLOCKS + count))
        else
            rm -f "${cache_file}.tmp"
            if [ -f "$cache_file" ]; then
                echo "GeoIP: WARNING — download failed for ${code}, using stale cache"
                count=$(wc -l < "$cache_file")
                TOTAL_BLOCKS=$((TOTAL_BLOCKS + count))
            else
                echo "GeoIP: WARNING — no data available for ${code}, skipping" >&2
                FAILED="${FAILED} ${code}"
                continue
            fi
        fi
    else
        count=$(wc -l < "$cache_file")
        echo "GeoIP: ${code} — ${count} CIDR blocks (from cache)"
        TOTAL_BLOCKS=$((TOTAL_BLOCKS + count))
    fi

    # Write rules to temp file (avoids slow O(n²) bash string concatenation)
    while IFS= read -r cidr; do
        [ -n "$cidr" ] && echo "    Require not ip ${cidr}" >> "$RULES_FILE"
    done < "$cache_file"
done

if [ ! -s "$RULES_FILE" ]; then
    echo "GeoIP: ERROR — no CIDR data available, geo-blocking not applied" >&2
    rm -f "$RULES_FILE" "$GEOIP_BLOCK_CONF"
    exit 1
fi

# Generate dedicated Apache config file
cat > "$GEOIP_BLOCK_CONF" <<EOF
# Auto-generated by init_geoip.sh — do not edit manually
# Blocked countries: ${BLOCKED_COUNTRIES}
# Last updated: $(date -u '+%Y-%m-%d %H:%M UTC')
# Total CIDR blocks: ${TOTAL_BLOCKS}

<Location />
  <RequireAll>
    Require all granted
$(cat "$RULES_FILE")
  </RequireAll>
</Location>
EOF

rm -f "$RULES_FILE"

echo "GeoIP: blocking active — ${TOTAL_BLOCKS} CIDR blocks for: ${BLOCKED_COUNTRIES}"
if [ -n "$FAILED" ]; then
    echo "GeoIP: WARNING — missing data for:${FAILED}" >&2
fi
